import fs from 'fs';
import path from 'path';
import ignore from 'ignore';
import { readGitignore, isIgnored } from './fileUtils.js';
import { ALWAYS_IGNORE, ASTROLARK_MARKER } from './constants.js';

export function generateOverview(rootPath: string): {
  content: string,
  ignoredFiles: Map<string, string[]>
} {
  const gitignorePatterns = readGitignore(rootPath);
  const ig = ignore().add(gitignorePatterns).add(ALWAYS_IGNORE);
  let structure: string[] = [];
  let files: { [key: string]: string } = {};
  let ignoredFiles: Map<string, string[]> = new Map();

  function traverseDirectory(dir: string, depth: number = 0): void {
    const filesInDir = fs.readdirSync(dir);
    filesInDir.forEach((file, index) => {
      const filePath = path.join(dir, file);
      const relativePath = path.relative(rootPath, filePath);

      if (isIgnored(filePath, rootPath, ig)) {
        ignoredFiles.set(relativePath, ['ignored']);
        return;
      }

      const isLast = index === filesInDir.length - 1;
      const prefix = '  '.repeat(depth) + (isLast ? '└─ ' : '├─ ');
      structure.push(`${prefix}${file}`);

      if (fs.statSync(filePath).isDirectory()) {
        traverseDirectory(filePath, depth + 1);
      } else {
        const content = fs.readFileSync(filePath, 'utf-8');
        files[relativePath] = content;
      }
    });
  }

  traverseDirectory(rootPath);

  // Generate META-INFO content
  const metaInfo = `@@ALK<META-INFO>
ABOUT_ASTROLARK: This file was generated by Astrolark.
BASE_PATH: ${rootPath}
STRUCTURE:
${structure.join('\n')}
@@ALK</META-INFO>
`;

  // Generate Astrolark format content
  let content = `# ${ASTROLARK_MARKER}\n\n`;
  content += metaInfo + '\n';

  for (const [filePath, fileContent] of Object.entries(files)) {
    content += `@@ALK<FILE path="${filePath}">\n${fileContent}\n@@ALK</FILE>\n\n`;
  }

  return { content, ignoredFiles };
}
